#!/bin/sh

# Copyright © 2019 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

set -e -u

prog="${0##*/}"
if [ $# -ne 1 ]
then
    printf 'Usage: %s ARCHIVE-URL\n' "$prog" >&2
    exit 1
fi
archive_url="$1"
orig_url=$(sed -E -e 's!^https://web[.]archive[.]org/web/[0-9]+/!!' <<EOF
$archive_url
EOF
)
if [ "$orig_url" = "$archive_url" ]
then
    printf '%s: unsupported URL: %s\n' "$prog" "$archive_url" >&2
    exit 1
fi
tmpdir=$(mktemp -d -t "$prog.XXXXXX")
cd "$tmpdir"
wget -nv "$orig_url" -O original
wget -nv "$archive_url" -O archived
sha256sum original archived
diff -u original archived
rm -r "$tmpdir"

# vim:ts=4 sts=4 sw=4 et
