#!/bin/sh

# Copyright © 2019 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

set -e -u

prog="${0##*/}"
if [ $# -ne 1 ]
then
    printf 'Usage: %s ARCHIVE-URL\n' "$prog" >&2
    exit 1
fi
archive_url="$1"
s="${archive_url#https://web.archive.org/web/}"
if [ "$s" = "$archive_url" ]
then
    printf '%s: unsupported URL: %s\n' "$prog" "$archive_url" >&2
    exit 1
fi
s=$(sed -E -e 's/^([0-9]{4})([0-9]{2})([0-9]{2}).*/\1 \2 \3/' <<EOF
$s
EOF
)
read -r y m d <<EOF
$s
EOF
printf 'archive-url=%s|archive-date=%s-%s-%s\n' "$archive_url" "$y" "$m" "$d"

# vim:ts=4 sts=4 sw=4 et
